### ISSUE TITLE
documentation: README completness, debug ocrd-tool.json

### ISSUE THREAD

**Issue by tboenig** [OCR-D/ocrd_segment#13]
Please debug your ocrd_tool.json file. 
I found  an error:  
``` xml
<report valid="false">
  <error>[tools.ocrd-segment-evaluate] 'output_file_grp' is a required property</error>
</report>
```
You can find the ocrd-tool.json documentation: https://ocr-d.github.io/ocrd_tool

Please check your README file and complet them. An ideal README file look like:
 ```md
# Name of application


## Introduction
...

## Installation
...

## Usage
...

## Testing
...
```
Thank you very much.

**Comment by bertsky** [comment]
This is an error of the validator in core, not of this repo. See OCR-D/core#295. Closing.

**Comment by tboenig** [comment]
For the error that's true, but look at the README file please and complete it. Thank you.
