### ISSUE TITLE
Update README, only announce features that are acutally provided

### ISSUE THREAD

**Issue by dariok** [OCR-D/ocrd_segment#16]
README announces `ocrd-segment-via-template` and `ocrd-segment-via-model`  – none of which are actually provided by this package.
It does provide some `ocrd-segment-extract-*` features; these do not do any segmentation though (or I could not find out how).

**Comment by kba** [comment]
Keep in mind that this is not an official OCR-D project, but a side project by @wrznr and @bertsky. Which does not mean that it wasn't great software (it is!) just that documentation and support won't be as much of a priority as for official projects.

That being said, the [`ocrd-tool.json`](https://github.com/OCR-D/ocrd_segment/blob/master/ocrd_segment/ocrd-tool.json) is the best way to understand which processors come with a project, their parameters etc.

**Comment by bertsky** [comment]
Thanks, I just updated the README anyway.

**Comment by dariok** [comment]
@kba True, but the first thing someone sees when going to github to clone the repo is the content of README – as I came here via gitbub.co/OCR-D, I only noticed that after cloning.

@bertsky thanks!
