### ISSUE TITLE
Expand regions via repair/sanitize

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_segment#21]
Before samitization:
![image](https://user-images.githubusercontent.com/26707219/70433301-a768fb80-1a81-11ea-95cd-e7fdccff0adc.png)

Regions are often too small and do not span the lines they (should) contain.

After sanitization:
![image](https://user-images.githubusercontent.com/26707219/70433221-7092e580-1a81-11ea-9caa-1f1bf6f90f4e.png)

Situation is not much better, although
```shell
$ ocrd-segment-repair -J
...
"sanitize": {
   "type": "boolean",
   "default": false,
   "description": "Shrink and/or expand a region in such a way that it coordinates include those of all its lines"
  }
...
```

Expansion does not work, is not complete.

**Comment by bertsky** [comment]
Yes, expansion currently cannot extend the bounding box of the original region. (`sanitize_page` cannot operate on the region image array, it must use the page image array...)

**Comment by wrznr** [comment]
But `sanitize_page` iterates over regions and lines within regions and changes the coordinates of the regions. It looks like expansion could be easily added.

**Comment by bertsky** [comment]
Expansion of the region polygon was already there, but only up to the region _bbox_.

Please try #22!

**Comment by wrznr** [comment]
![image](https://user-images.githubusercontent.com/26707219/70434952-ec8f2c80-1a85-11ea-9918-e76295e2cd09.png)
 Perfect!
