### ISSUE TITLE
`ocrd-segment-extract-pages` does not support `--help` option

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_segment#30]
It fails with a `KeyError` exception.

**Comment by stweil** [comment]
It looks like `ocrd-tool.json` needs an update.

**Comment by bertsky** [comment]
Thanks @stweil, and sorry for the inconvenience!

Fixed in 14fc19c96.

**Comment by stweil** [comment]
@bertsky, I can see that commit on GitHub, but not on the master branch and not in local clone.

**Comment by bertsky** [comment]
> I can see that commit on GitHub, but not on the master branch and not in local clone.

Sorry about that, please try again now.
