### ISSUE TITLE
change default output filegroup for `ocrd-segment-replace-original`

### ISSUE THREAD

**Issue by EEngl52** [OCR-D/ocrd_segment#39]
The default output filegroup for `ocrd-segment-replace-original` is set to `OCR-D-IMG-CROP` which already exists in the majority of METS-files. Would be great to change the default value, so a user is not forced to specify it on his own (as for the other processors this is purely optional). 
@kba suggested, that changing the default value might actually not be necessary, if we could drop the rule for two output filegroups also for this processor.

**Comment by bertsky** [comment]
Yes, I fully agree. Maybe we can skip the intermediate step of fixing with another `OCR-D-IMG-*` fileGrp by using the output fileGrp right away.

I don't know for sure ATM whether the latter depends on anything from core, so let's do this is PRs (across all modules) and test first...

**Comment by bertsky** [comment]
@EEngl52 is this urgent – does your workflow already depend on `ocrd-segment-replace-original`? If so, would you prefer a PR here (for using the output fileGrp), or a direct fix (switching to, say, `OCR-D-IMG-SUBST`)?

**Comment by EEngl52** [comment]
@bertsky  it is definitely not urgent. I just wanted to try out the new processors (which work perfectly fine btw 😃) before I add them to our workflow section on the website. For now, I will just add the second output fileGrp to the example call. Would just be nice to drop it in the future

**Comment by bertsky** [comment]
Ok, you convinced me to make a quick-fix here (before others fall into this trap based on our documentation, or we have to bloat the documentation). See current master. Feel free to re-open if this is not satisfactory.
