### ISSUE TITLE
cannot upload to pypi anymore

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_segment#53]
The change https://github.com/OCR-D/ocrd_segment/commit/c8756272caf900febe7166f8bed5d20713f002cf depends on https://github.com/ppwwyyxx/cocoapi/pull/7, an addition of mine to the current pycocotools version 2.0.3 on PyPI. Such git URL references are allowed in requirements.txt / setuptools, but the PyPI server refuses taking such builds:

```
Invalid value for requires_dist. Error: Can't have direct dependency: 'pycocotools @ git+https://github.com/bertsky/pycocotools#subdirectory=PythonAPI'
```

@kba, do you know what to do under such circumstances?

**Comment by kba** [comment]
AFAIK there is no workaround, PyPI does not allow `git+ssh`/`git+https`/... requirements for security reasons.

What we've done in the past is publish the referenced, forked version to PyPI, with an `ocrd-fork-` prefix. I.e. edit the `name` in `setup.py` in https://github.com/bertsky/pycocotools (which is private BTW), bump the version, publish that and then reference `ocrd-fork-pycocotools` in ocrd_segments's requirements.txt.

**Comment by bertsky** [comment]
Thank you – did all that, too.
