### ISSUE TITLE
ocrd-segment-extract-lines ignores lines with "\n" in <TextEquiv><Unicode>

### ISSUE THREAD

**Issue by stefanCCS** [OCR-D/ocrd_segment#58]
I have used `ocrd-segment-extract-lines` with a PAGE file, which has had some `<TextLine>` with a "\n" in the `<Unicode>`area.
Unfortunately, for these lines the extraction is not done.

This example works ok:```

        <pc:TextEquiv>
          <pc:Unicode>1889</pc:Unicode>
        </pc:TextEquiv>

```
This example does not work:
```
        <pc:TextEquiv>
          <pc:Unicode>1889
          </pc:Unicode>
        </pc:TextEquiv>
```

==> please clarify ...

**Comment by bertsky** [comment]
Oh, now I see it myself: the newline is incidental. Starting with v0.1.15, the lines are not extracted unless they meet the filter criteria controlled for by the tool json parameters `min-line-length` (default 5), `min-line-width` and `min-line-height`.

Sorry for the inconvenience – I should have set that conservatively to 1/1/1 (merely to avoid errors).

**Comment by stefanCCS** [comment]
yes, thats it - works now correctly.

**Comment by bertsky** [comment]
Note: I have relaxed the defaults to 0/1/1 in the master version.
